### ISSUE TITLE
Pop up on arrival telling them to allow the browser to detect their location 

### ISSUE THREAD

**Issue by csharpd** [csharpd/feedme#5]
Otherwize the app doesn't work

**Comment by ecomba** [comment]
There is already the popup asking for the location... 

Would it not be better to change the empty page that we have now full of cats wanting to eat with a page that tells you what's going on and why you might want to let the app locate you @csharpd ?

**Comment by csharpd** [comment]
I like the cats

**Comment by csharpd** [comment]
@ecomba How about a message and one cat at the bottom of the message? :)

**Comment by ecomba** [comment]
Maybe, I will play a little around with this and see how the :cat: behaves :smile:
